export let list = [
  {
    key: "p1",
    projectName: "Expense Trcker",
    langUsed: "React",
    projectDesc: "This is a simple project created using React.",
    gitRepoLink: "https://github.com/prakhargaba007/expense-trcker",
    gitPages: "https://prakhargaba007.github.io/expense-trcker/",
  },
  {
    key: "p2",
    projectName: "Final Countdown",
    langUsed: "React",
    projectDesc: "This is a simple project created using React.",
    gitRepoLink: "https://github.com/prakhargaba007/Final-Countdown",
    gitPages: "https://prakhargaba007.github.io/Final-Countdown/",
  },
  {
    key: "p5",
    projectName: "Place Picker",
    langUsed: "React",
    projectDesc: "This is a simple project created using React.",
    gitRepoLink: "https://github.com/prakhargaba007/Place-Picker",
    gitPages: "https://prakhargaba007.github.io/Place-Picker/",
  },
  {
    key: "p3",
    projectName: "Investment Calculator",
    langUsed: "React",
    projectDesc: "This is a simple project created using React.",
    gitRepoLink: "https://github.com/prakhargaba007/investment-calculator",
    gitPages: "https://prakhargaba007.github.io/investment-calculator/",
  },
  {
    key: "p4",
    projectName: "Login Page",
    langUsed: "React",
    projectDesc: "This is a simple project created using React.",
    gitRepoLink: "https://github.com/prakhargaba007/Login-Page",
    gitPages: "https://prakhargaba007.github.io/Login-Page/",
  },
  {
    key: "p6",
    projectName: "Quiz App",
    langUsed: "React",
    projectDesc: "This is a simple project created using React.",
    gitRepoLink: "https://github.com/prakhargaba007/Quiz-App",
    gitPages: "https://prakhargaba007.github.io/Quiz-App/",
  },
  {
    key: "p7",
    projectName: "React Counter",
    langUsed: "React",
    projectDesc: "This is a simple project created using React.",
    gitRepoLink: "https://github.com/prakhargaba007/React-Counter",
    gitPages: "https://prakhargaba007.github.io/React-Counter/",
  },
  {
    key: "p8",
    projectName: "Shooping Website",
    langUsed: "React",
    projectDesc: "This is a simple project created using React.",
    gitRepoLink: "https://github.com/prakhargaba007/Shooping-Website",
    gitPages: "https://prakhargaba007.github.io/Shooping-Website/",
  },
  {
    key: "p9",
    projectName: "Tic Tac Toe",
    langUsed: "React",
    projectDesc: "This is a simple project created using React.",
    gitRepoLink: "https://github.com/prakhargaba007/tic-tac-toe",
    gitPages: "https://prakhargaba007.github.io/tic-tac-toe/",
  },
  {
    key: "p10",
    projectName: "Task Tracker",
    langUsed: "React",
    projectDesc: "This is a simple project created using React.",
    gitRepoLink: "https://github.com/prakhargaba007/Task-Tracker",
    gitPages: "https://prakhargaba007.github.io/Task-Tracker/",
  },
  {
    key: "p11",
    projectName: "UsabilityHub Dummy Project",
    langUsed: "React",
    projectDesc: "This is a simple project created using React.",
    gitRepoLink: "https://github.com/prakhargaba007/UsabilityHub-dummy-project",
    gitPages: "https://prakhargaba007.github.io/UsabilityHub-dummy-project/",
  },
  {
    key: "p12",
    projectName: "E-Commerce with payment",
    langUsed: "React",
    projectDesc: "This is a simple project created using React.",
    gitRepoLink: "https://github.com/prakhargaba007/e-commerce",
    gitPages: "https://e-commercee-anhs.onrender.com/",
  },
];
